/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.PressaoArterialController;
import entity.PressaoArterial;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yagos
 */
public class TelaExclusao extends javax.swing.JFrame {
    PressaoArterialController pac;
    /**
     * Creates new form TelaExclusao
     */
    public TelaExclusao() {
        initComponents();
    }

    public TelaExclusao(PressaoArterialController pac) {
        initComponents();
        this.pac = pac;

        DefaultTableModel tabPressao = (DefaultTableModel) tblPressaoEx.getModel();
        for (PressaoArterial listaPa : pac.findAll()){
            Object[] pressaoArterial = new Object[]{
                    listaPa.getId(),
                    listaPa.getValorPressao(),
                    listaPa.getData(),
                    listaPa.getHora()
            };

            tabPressao.addRow(pressaoArterial);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPressaoEx = new javax.swing.JTable();
        btnFecharEx = new javax.swing.JButton();
        btnExcluirEx = new javax.swing.JButton();
        btnApagarTudoEx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TELA DE EXCLUSÃO");

        tblPressaoEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pressão Arterial", "Data", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPressaoEx);

        btnFecharEx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFecharEx.setText("FECHAR");
        btnFecharEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharExActionPerformed(evt);
            }
        });

        btnExcluirEx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirEx.setText("EXCLUIR");
        btnExcluirEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirExActionPerformed(evt);
            }
        });

        btnApagarTudoEx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnApagarTudoEx.setText("APAGAR TUDO");
        btnApagarTudoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTudoExActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnApagarTudoEx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirEx)
                .addGap(33, 33, 33)
                .addComponent(btnFecharEx)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharEx)
                    .addComponent(btnExcluirEx)
                    .addComponent(btnApagarTudoEx))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharExActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharExActionPerformed

    private void btnExcluirExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirExActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExcluirExActionPerformed

    private void btnApagarTudoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTudoExActionPerf3ormed
        // TODO add your handling code here:
        int resultadoConfirm = JOptionPane.showConfirmDialog(this, "Deseja mesmo apagar todos os registros?");

        if (resultadoConfirm == 0){
            if (pac.excluirTudo()){
                JOptionPane.showMessageDialog(this, "Registros apagados!");
            }else {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro. Não foi possível apagar os registros!");
            }
        }
    }//GEN-LAST:event_btnApagarTudoExActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExclusao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarTudoEx;
    private javax.swing.JButton btnExcluirEx;
    private javax.swing.JButton btnFecharEx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblPressaoEx;
    // End of variables declaration//GEN-END:variables
}
